In [1]:
import torch 

In [12]:
### Without Reparamaterization ###
input_tensor = torch.tensor([3.])
w1 = torch.tensor([2.], requires_grad=True)
w_mu = torch.tensor([8.], requires_grad=True)
w_sd = torch.tensor([9.], requires_grad=True)

w1_out = w1*input_tensor
mu = w_mu*w1_out
std = w_sd*w1_out

z = torch.normal(mean=mu, std=std)

z.backward()

print("Propogated Gradient without Reparam. Trick", w1.grad)

### With Reparamaterization ###
w1_out = w1*input_tensor
mu = w_mu*w1_out
std = w_sd*w1_out

z = mu + std*torch.randn(1)

z.backward()

print("Propogated Gradient with Reparam. Trick", w1.grad)

Propogated Gradient without Reparam. Trick tensor([0.])
Propogated Gradient with Reparam. Trick tensor([38.5051])


In [4]:
print(w1)
print(w_mu)
print(w_sd)

tensor([2.], requires_grad=True)
tensor([8.], requires_grad=True)
tensor([9.], requires_grad=True)


In [6]:
print(w1_out)
print(mu)
print(std)

tensor([6.], grad_fn=<MulBackward0>)
tensor([48.], grad_fn=<MulBackward0>)
tensor([54.], grad_fn=<MulBackward0>)


In [10]:
print(w1.grad)

tensor([0.])
